=== laurenfissel11-ux/SII_Assignment_group_7_ex5/schema_LF.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="train_station">
        <xs:complexType>
            <xs:sequence>
                <!--city, simple element type-->
                <xs:element name="city" type="xs:string"/>
                <!--coordinates, complex element type-->
                <xs:element name="coordinates">
                    <xs:complexType>
                        <xs:sequence>
                            <!--longitude & latitude, simple element types-->
                            <xs:element name="longitude" type="xs:decimal"/>
                            <xs:element name="latitude" type="xs:decimal"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <!--trainLines, complex element type-->
                <xs:element name="trainLines">
                    <xs:complexType>
                        <xs:sequence>
                            <!--trainLine, complex element type-->
                            <xs:element name="trainLine" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <!--"to" & "from" simple element types-->
                                        <xs:element name="from" type="xs:string"/>
                                        <xs:element name="to" type="xs:string"/>
                                    </xs:sequence>
                                    <!--trainLine id attribute-->
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <!--train_station id attribute-->
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== laurenfissel11-ux/SII_Assignment_group_7_ex5/station_LF.xml
<?xml version="1.0" encoding="UTF-8"?> <!--XML Prolog, optional-->
<train_station 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="schema_LF.xsd"
    id="01">
    <!--Root element complete-->

    <city>MÃ¼nster</city>

    <coordinates>
        <longitude>7.6261</longitude>
        <latitude>51.9607</latitude>
    </coordinates>

    <trainLines>
        <trainLine id="01">
            <from>City1</from>
            <to>City2</to>
        </trainLine>
        <trainLine id="01">
            <from>City3</from>
            <to>City4</to>
        </trainLine>
    </trainLines>

</train_station>
